import uuid
from datetime import date
from typing import Dict, Any

from blog_app.graph.builder import GraphBuilder


def run_blog_pipeline(
    topic: str,
    run_id: str,
    as_of: str | None = None,
    images_enabled: bool = False,
    provider: str | None = None,
) -> Dict[str, Any]:
    """
    Runs the blog generation pipeline end-to-end.

    This function is intentionally framework-agnostic.
    It can be reused by FastAPI, CLI, tests, etc.
    
    Args:
        topic: The blog topic
        run_id: Unique identifier for this run (generated by caller)
        as_of: Date string for recency
        images_enabled: Whether to generate images for the blog
        provider: LLM provider override (google or groq). If None, uses config.yaml.
    """

    if not topic or not topic.strip():
        raise ValueError("Topic must be a non-empty string.")
    
    if not run_id or not run_id.strip():
        raise ValueError("run_id must be a non-empty string.")

    # -----------------------------
    # Override LLM if provider specified
    # -----------------------------
    if provider:
        from blog_app.llm import client as llm_client_module
        loader = llm_client_module.ModelLoader()
        llm_client_module.llm = loader.load_llm(provider_override=provider)

    # -----------------------------
    # Build graph (once per process)
    # -----------------------------
    graph_builder = GraphBuilder()
    app = graph_builder.build()

    inputs: Dict[str, Any] = {
        "topic": topic.strip(),
        "run_id": run_id.strip(),
        # routing / research
        "mode": "",
        "needs_research": False,
        "queries": [],
        "evidence": [],
        "plan": None,

        # recency
        "as_of": as_of or date.today().isoformat(),
        "recency_days": 7,

        # workers
        "sections": [],

        # reducer / images
        "images_enabled": images_enabled,
        "merged_md": "",
        "md_with_placeholders": "",
        "image_specs": [],

        # final output
        "final": "",
    }

    # Run graph (non-streaming execution)
    output = app.invoke(inputs)

    return output


if __name__ == "__main__":
    # Generate run_id for CLI execution
    test_run_id = uuid.uuid4().hex[:8]
    
    result = run_blog_pipeline(
        topic="How LangGraph enables agentic workflows",
        run_id=test_run_id,
    )

    print("\n===== BLOG GENERATED =====\n")
    print(result.get("final", "No output generated"))
