import os
import sys
from dotenv import load_dotenv

from blog_app.config.config_loader import read_yaml
from blog_app.config.paths_config import *

from pathlib import Path
from typing import List

from blog_app.logger.custom_logger import CustomLogger
from blog_app.exception.custom_exception import CustomException

logger = CustomLogger().get_logger(__name__)
load_dotenv()

class ImageService:
    """
    Handles image generation and markdown image application.
    Owns all Gemini-related logic.
    """
    def __init__(self, images_dir: Path):
        self.config = read_yaml(CONFIG_PATH)["images_model"]
        self.images_dir = images_dir
        self.images_dir.mkdir(exist_ok=True)

    def _gemini_generate_image_bytes(self, prompt: str) -> bytes:
        """
        Returns raw image bytes generated by Gemini.

        """
        try:
            from google import genai
            from google.genai import types

            api_key = os.environ.get("GOOGLE_API_KEY")
            if not api_key:
                logger.error("GOOGLE_API_KEY error")
                raise RuntimeError("GOOGLE_API_KEY is not set.")

            client = genai.Client(api_key=api_key)

            logger.info("Generating image via Gemini")

            resp = client.models.generate_content(
                model=self.config['model_name'],
                contents=prompt,
                config=types.GenerateContentConfig(
                    response_modalities=["IMAGE"],
                    safety_settings=[
                        types.SafetySetting(
                            category="HARM_CATEGORY_DANGEROUS_CONTENT",
                            threshold="BLOCK_ONLY_HIGH",
                        )
                    ],
                ),
            )

           
            parts = getattr(resp, "parts", None)
            if not parts and getattr(resp, "candidates", None):
                try:
                    parts = resp.candidates[0].content.parts
                except Exception:
                    parts = None

            if not parts:
                raise RuntimeError("No image content returned (safety/quota/SDK change).")

            for part in parts:
                inline = getattr(part, "inline_data", None)
                if inline and getattr(inline, "data", None):
                    return inline.data

            raise RuntimeError("No inline image bytes found in response.")
        except Exception as e:
            logger.error(f"Error during generating image bytes : {e}")
            raise CustomException("Failed during generating image bytes", sys)

    def apply_images_to_markdown(self, md: str, image_specs: List[dict]) -> str:
        """
        Applies image placeholders to markdown.
        Derived directly from reducer logic.
        """
        for spec in image_specs:
            placeholder = spec["placeholder"]
            filename = spec["filename"]
            out_path = self.images_dir / filename

            # generate only if needed
            if not out_path.exists():
                try:
                    img_bytes = self._gemini_generate_image_bytes(spec["prompt"])
                    out_path.write_bytes(img_bytes)
                    logger.info(f"Image written: {filename}")

                except Exception as e:
                    logger.error(f"Image generation failed for {filename}: {e}")
                    # graceful fallback: keep doc usable
                    prompt_block = (
                        f"> **[IMAGE GENERATION FAILED]** {spec.get('caption','')}\n>\n"
                        f"> **Alt:** {spec.get('alt','')}\n>\n"
                        f"> **Prompt:** {spec.get('prompt','')}\n>\n"
                        f"> **Error:** {e}\n"
                    )
                    md = md.replace(placeholder, prompt_block)
                    continue

            img_md = f"![{spec['alt']}](../images/{filename})\n*{spec['caption']}*"
            md = md.replace(placeholder, img_md)
        return md
